@startuml ユースケース図
left to right direction
actor 申請者
actor 交通費精算システム
actor 承認者
actor 経理担当者
rectangle 出張申請システム {
usecase 出張申請を登録
usecase 出張申請を提出
usecase 出張申請を承認
usecase 出張申請を却下
usecase 出張申請を差し戻す
usecase 出張申請を確認
}
申請者 --> 出張申請を登録
出張申請を登録 <-- 交通費精算システム
申請者 --> 出張申請を提出
承認者 --> 出張申請を承認
承認者 --> 出張申請を却下
承認者 --> 出張申請を差し戻す
承認者 --> 出張申請を確認
経理担当者 --> 出張申請を確認
@enduml