@startuml ホテル利用者と部屋と予約
class 利用者{
    - 名前
    - 住所
    - 電話番号
}
class ホテル{
    - 部屋
}
class 部屋{
    - タイプ
    - 価格
    - キャンペーン価格
}
class 予約{
    - チェックイン日
    - 滞在期間
    - 値段
}
部屋 "*" -ri- "1" ホテル
利用者 o-- 予約
@enduml